// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xCF05 },
    { 3, 0xDDC0 },
    { 3, 0xEC7B },
    { 4, 0xC000 },
    { 4, 0xCEA8 },
    { 4, 0xD71A },
    { 4, 0xDF03 },
    { 4, 0xE660 },
    { 4, 0xED36 },
    { 4, 0xF40C },
    { 6, 0xC000 },
    { 6, 0xC670 },
    { 6, 0xCCDD },
    { 6, 0xD331 },
    { 6, 0xD939 },
    { 3, 0xFB36 },
    { 4, 0xFA84 },
    { 4, 0xFD93 },
    { 4, 0xFE72 },
    { 4, 0xFF2B }
};

#define LEVEL0C_BIN                     0
#define LEVEL2C_BIN                     1
#define LEVEL3C_BIN                     2
#define LEVEL4C_BIN                     3
#define LEVEL1C_BIN                     4
#define ZONEA_BIN                       5
#define ZONEB_BIN                       6
#define INTRO7_BIN                      7
#define INTRO5_BIN                      8
#define INTRO6_BIN                      9
#define INTRO2_BIN                      10
#define ENDING_BIN                      11
#define INTRO4_BIN                      12
#define INTRO3_BIN                      13
#define INTRO1_BIN                      14
#define DEDICADO_BIN                    15
#define LOGO_BIN                        16
#define CONTROLS_BIN                    17
#define MARCO_BIN                       18
#define LEVEL_SCREEN_TSC_BIN            19
#define TITLE_BIN                       20

