// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xCF99 },
    { 3, 0xDEBF },
    { 3, 0xEDC4 },
    { 4, 0xC000 },
    { 4, 0xCEBB },
    { 4, 0xD72D },
    { 4, 0xDF16 },
    { 4, 0xE673 },
    { 4, 0xED49 },
    { 4, 0xF41F },
    { 6, 0xC000 },
    { 6, 0xC670 },
    { 6, 0xCCDD },
    { 6, 0xD331 },
    { 6, 0xD939 },
    { 4, 0xFA97 },
    { 3, 0xFC7F },
    { 4, 0xFF02 },
    { 6, 0xDF33 },
    { 6, 0xDFEC }
};

#define LEVEL1C_BIN                     0
#define LEVEL2C_BIN                     1
#define LEVEL0C_BIN                     2
#define LEVEL3C_BIN                     3
#define LEVEL4C_BIN                     4
#define ZONEA_BIN                       5
#define ZONEB_BIN                       6
#define INTRO7_BIN                      7
#define INTRO5_BIN                      8
#define INTRO6_BIN                      9
#define INTRO2_BIN                      10
#define ENDING_BIN                      11
#define INTRO4_BIN                      12
#define INTRO3_BIN                      13
#define INTRO1_BIN                      14
#define DEDICADO_BIN                    15
#define LOGO_BIN                        16
#define CONTROLS_BIN                    17
#define MARCO_BIN                       18
#define LEVEL_SCREEN_TSC_BIN            19
#define TITLE_BIN                       20

